### PR TITLE
Sync GM view with Player Token

### PR DESCRIPTION
**Pull request by mouse0270**
Added the option to Sync the Game Master View with a specific Player Token. 
German Translation is Google Generated.

### CODE REVIEW

**Comment by theripper93** [comment]
i'm sorry if i was not clear but i'm not adding these kind of features to the module itself, if i start allowing that i risk getting bloat in the module, i'll keep in mind this pull request and consider adding it in the future if there is real demand for it ;)

**Comment by mouse0270** [comment]
No worries, this was mostly meant for me. Github was set to autocreate pull request for the main thread. The fact I did this as a fork and pull request simply means when you update I can merge you additions with this change for me.

It makes it so when you do your frequent updates I don't have to constantly keep redoing my code to add this functionality.

**Comment by theripper93** [comment]
Ok, I would suggest if you have the time, that you could make it into a sort of add on (separate module) and post it on the discord - if you need help feel free to ask on discord

**Comment by mouse0270** [comment]
I'd love to but I would need to figure out how to check and see when the level is changed from the GM's perspective... I don't really see any sort of API attached to the levels module.

**Comment by theripper93** [comment]
You can just replace the function ;) something like LevelsUi.prototype.function = yourfunction

**Comment by mouse0270** [comment]
Clever, it would risk updates to levels more easily breaking it, but honestly all of these changes are like 30 lines... Easy enough to fix.

I work on doing that now. Got nothing better to do right now anyways. lol

**Pull request closed without merging**
